export interface CharacterData {
  id: string;
  name: string;
  groundCC: string;
  shortHopCC: string;
  clayCC: string;
  clayStanding: string;
  ledgeSideTiltKO: string;
  ledgeAirKO: string;
  upSmashKO: string;
  ledgeSideSmashKO: string;
  upAirStrongKO: string;
  clayToSideSmash: string;
  ccToSideSmash: string;
  ledgesideAerialMeteor: string;
  sombrero: string;
  airNDown: string;
  airNWeakDown: string;
  upThrowThunder: string;
  downAirUpStrong: string;
  ledgeSteal: string;
  fastestLedgeStealInside: string;
  slowestLedgeStealInside: string;
  upAirNeutralAir: string;
}

export const charactersData: CharacterData[] = [
  {
    id: "1",
    name: "Mario",
    groundCC: "-",
    shortHopCC: "41-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "145",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "101-117",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "75",
    sombrero: "150",
    airNDown: "34",
    airNWeakDown: "89",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: "○"
  },
  {
    id: "2",
    name: "Donkey Kong",
    groundCC: "-",
    shortHopCC: "41-88",
    clayCC: "",
    clayStanding: "88",
    ledgeSideTiltKO: "160",
    ledgeAirKO: "125",
    upSmashKO: "120",
    ledgeSideSmashKO: "95",
    upAirStrongKO: "121-141",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "170",
    airNDown: "40",
    airNWeakDown: "102",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "3",
    name: "Link",
    groundCC: "",
    shortHopCC: "43-78",
    clayCC: "",
    clayStanding: "78",
    ledgeSideTiltKO: "145",
    ledgeAirKO: "110",
    upSmashKO: "105",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "110-135",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "150",
    airNDown: "35",
    airNWeakDown: "92",
    upThrowThunder: "",
    downAirUpStrong: "✕",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "4",
    name: "Samus",
    groundCC: "",
    shortHopCC: "44-79",
    clayCC: "",
    clayStanding: "79",
    ledgeSideTiltKO: "150",
    ledgeAirKO: "120",
    upSmashKO: "110",
    ledgeSideSmashKO: "85",
    upAirStrongKO: "115-135",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "155",
    airNDown: "36",
    airNWeakDown: "94",
    upThrowThunder: "",
    downAirUpStrong: "✕",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "4.1",
    name: "Dark Samus",
    groundCC: "",
    shortHopCC: "44-80",
    clayCC: "",
    clayStanding: "79",
    ledgeSideTiltKO: "150",
    ledgeAirKO: "120",
    upSmashKO: "110",
    ledgeSideSmashKO: "85",
    upAirStrongKO: "115-135",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "155",
    airNDown: "36",
    airNWeakDown: "94",
    upThrowThunder: "",
    downAirUpStrong: "✕",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "5",
    name: "Yoshi",
    groundCC: "-",
    shortHopCC: "38-69",
    clayCC: "",
    clayStanding: "69",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "105",
    upSmashKO: "95",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-111",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "145",
    airNDown: "31",
    airNWeakDown: "83",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "6",
    name: "Kirby",
    groundCC: "",
    shortHopCC: "35-64",
    clayCC: "",
    clayStanding: "64",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-105",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "65",
    sombrero: "140",
    airNDown: "29",
    airNWeakDown: "77",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "7",
    name: "Fox",
    groundCC: "41-65",
    shortHopCC: "-",
    clayCC: "",
    clayStanding: "65",
    ledgeSideTiltKO: "120",
    ledgeAirKO: "95",
    upSmashKO: "90",
    ledgeSideSmashKO: "65",
    upAirStrongKO: "90-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "130",
    airNDown: "29",
    airNWeakDown: "79",
    upThrowThunder: "",
    downAirUpStrong: "※",
    ledgeSteal: "Very High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "8",
    name: "Pikachu",
    groundCC: "-",
    shortHopCC: "50-66",
    clayCC: "",
    clayStanding: "66",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "130",
    airNDown: "30",
    airNWeakDown: "80",
    upThrowThunder: "195",
    downAirUpStrong: "✕",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "○",
    upAirNeutralAir: ""
  },
  {
    id: "9",
    name: "Luigi",
    groundCC: "",
    shortHopCC: "55-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "100-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "10",
    name: "Ness",
    groundCC: "-",
    shortHopCC: "40-73",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "85",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "214",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "11",
    name: "Captain Falcon",
    groundCC: "-",
    shortHopCC: "60-78",
    clayCC: "",
    clayStanding: "78",
    ledgeSideTiltKO: "145",
    ledgeAirKO: "115",
    upSmashKO: "105",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "110-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "155",
    airNDown: "35",
    airNWeakDown: "92",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "12",
    name: "Jigglypuff",
    groundCC: "",
    shortHopCC: "27-37",
    clayCC: "",
    clayStanding: "61",
    ledgeSideTiltKO: "120",
    ledgeAirKO: "95",
    upSmashKO: "85",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "80-100",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "120",
    airNDown: "27",
    airNWeakDown: "75",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "13",
    name: "Peach",
    groundCC: "-",
    shortHopCC: "38-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "145",
    ledgeAirKO: "105",
    upSmashKO: "95",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "100-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "13.1",
    name: "Daisy",
    groundCC: "-",
    shortHopCC: "38-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "145",
    ledgeAirKO: "105",
    upSmashKO: "95",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "100-121",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "14",
    name: "Bowser",
    groundCC: "32-92",
    shortHopCC: "",
    clayCC: "",
    clayStanding: "92",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "130",
    upSmashKO: "125",
    ledgeSideSmashKO: "95",
    upAirStrongKO: "135-165",
    clayToSideSmash: "32-92",
    ccToSideSmash: "32-70",
    ledgesideAerialMeteor: "100",
    sombrero: "180",
    airNDown: "42",
    airNWeakDown: "106",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "15.0",
    name: "Ice Climbers (Duo)",
    groundCC: "",
    shortHopCC: "40-72",
    clayCC: "",
    clayStanding: "72",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "135",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "○",
    upAirNeutralAir: ""
  },
  {
    id: "15.1",
    name: "Ice Climbers (Solo)",
    groundCC: "",
    shortHopCC: "40-72",
    clayCC: "",
    clayStanding: "72",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "135",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "○",
    upAirNeutralAir: ""
  },
  {
    id: "16",
    name: "Sheik",
    groundCC: "-",
    shortHopCC: "62-66",
    clayCC: "",
    clayStanding: "66",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "95",
    upSmashKO: "90",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "85-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "130",
    airNDown: "29",
    airNWeakDown: "80",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "17",
    name: "Zelda",
    groundCC: "-",
    shortHopCC: "45-69",
    clayCC: "Unreliable",
    clayStanding: "69",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "100-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "135",
    airNDown: "31",
    airNWeakDown: "83",
    upThrowThunder: "205",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "18",
    name: "Dr. Mario",
    groundCC: "-",
    shortHopCC: "49-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "105-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "60",
    sombrero: "150",
    airNDown: "34",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "19",
    name: "Pichu",
    groundCC: "-",
    shortHopCC: "-",
    clayCC: "",
    clayStanding: "59",
    ledgeSideTiltKO: "110",
    ledgeAirKO: "85",
    upSmashKO: "80",
    ledgeSideSmashKO: "95",
    upAirStrongKO: "75-90",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "65",
    sombrero: "115",
    airNDown: "26",
    airNWeakDown: "72",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Very High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "20",
    name: "Falco",
    groundCC: "-",
    shortHopCC: "49-68",
    clayCC: "",
    clayStanding: "68",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "80",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "81",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "21",
    name: "Marth",
    groundCC: "-",
    shortHopCC: "52-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "100-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: "○"
  },
  {
    id: "21.1",
    name: "Lucina",
    groundCC: "-",
    shortHopCC: "52-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "96-119",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "✕",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: "○"
  },
  {
    id: "22",
    name: "Young Link",
    groundCC: "-",
    shortHopCC: "54-70",
    clayCC: "",
    clayStanding: "70",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "105",
    upSmashKO: "95",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "100-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "80",
    sombrero: "135",
    airNDown: "32",
    airNWeakDown: "83",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "23",
    name: "Ganondorf",
    groundCC: "-",
    shortHopCC: "39-84",
    clayCC: "",
    clayStanding: "84",
    ledgeSideTiltKO: "150",
    ledgeAirKO: "120",
    upSmashKO: "115",
    ledgeSideSmashKO: "85",
    upAirStrongKO: "120-140",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "160",
    airNDown: "38",
    airNWeakDown: "98",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "24",
    name: "Mewtwo",
    groundCC: "-",
    shortHopCC: "36-66",
    clayCC: "",
    clayStanding: "66",
    ledgeSideTiltKO: "120",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "85-105",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "130",
    airNDown: "29",
    airNWeakDown: "79",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "25",
    name: "Roy",
    groundCC: "-",
    shortHopCC: "63-74",
    clayCC: "",
    clayStanding: "74",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-125",
    clayToSideSmash: "50-74",
    ccToSideSmash: "48-60",
    ledgesideAerialMeteor: "65",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "219",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "25.1",
    name: "Chrom",
    groundCC: "-",
    shortHopCC: "63-74",
    clayCC: "",
    clayStanding: "74",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-125",
    clayToSideSmash: "50-74",
    ccToSideSmash: "48-60",
    ledgesideAerialMeteor: "75",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "219",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "26",
    name: "Mr. Game & Watch",
    groundCC: "-",
    shortHopCC: "35-65",
    clayCC: "",
    clayStanding: "65",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "95",
    upSmashKO: "85",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "85-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "130",
    airNDown: "29",
    airNWeakDown: "78",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "27",
    name: "Meta Knight",
    groundCC: "-",
    shortHopCC: "51-67",
    clayCC: "",
    clayStanding: "67",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "95-120",
    clayToSideSmash: "45-50",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "80",
    sombrero: "130",
    airNDown: "30",
    airNWeakDown: "80",
    upThrowThunder: "196",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "28",
    name: "Pit",
    groundCC: "",
    shortHopCC: "40-74",
    clayCC: "",
    clayStanding: "74",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "90",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "28.1",
    name: "Dark Pit",
    groundCC: "",
    shortHopCC: "40-74",
    clayCC: "",
    clayStanding: "74",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "90",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "29",
    name: "Zero Suit Samus",
    groundCC: "",
    shortHopCC: "45-67",
    clayCC: "",
    clayStanding: "67",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "75",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "80",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "30",
    name: "Wario",
    groundCC: "",
    shortHopCC: "59-79",
    clayCC: "",
    clayStanding: "79",
    ledgeSideTiltKO: "150",
    ledgeAirKO: "115",
    upSmashKO: "105",
    ledgeSideSmashKO: "85",
    upAirStrongKO: "110-140",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "100",
    sombrero: "155",
    airNDown: "36",
    airNWeakDown: "93",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "31",
    name: "Snake",
    groundCC: "-",
    shortHopCC: "43-77",
    clayCC: "",
    clayStanding: "77",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "105",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "35",
    airNWeakDown: "91",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "32",
    name: "Ike",
    groundCC: "-",
    shortHopCC: "42-81",
    clayCC: "",
    clayStanding: "81",
    ledgeSideTiltKO: "150",
    ledgeAirKO: "120",
    upSmashKO: "110",
    ledgeSideSmashKO: "85",
    upAirStrongKO: "115-140",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "155",
    airNDown: "37",
    airNWeakDown: "95",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "33",
    name: "Squirtle",
    groundCC: "-",
    shortHopCC: "37-67",
    clayCC: "",
    clayStanding: "67",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "80",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "34",
    name: "Ivysaur",
    groundCC: "-",
    shortHopCC: "39-72",
    clayCC: "",
    clayStanding: "72",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "100-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "145",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "35",
    name: "Charizard",
    groundCC: "-",
    shortHopCC: "41-82",
    clayCC: "",
    clayStanding: "82",
    ledgeSideTiltKO: "150",
    ledgeAirKO: "120",
    upSmashKO: "115",
    ledgeSideSmashKO: "85",
    upAirStrongKO: "115-140",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "160",
    airNDown: "37",
    airNWeakDown: "97",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "36",
    name: "Diddy Kong",
    groundCC: "-",
    shortHopCC: "40-69",
    clayCC: "",
    clayStanding: "69",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "80",
    sombrero: "135",
    airNDown: "31",
    airNWeakDown: "83",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "37",
    name: "Lucas",
    groundCC: "-",
    shortHopCC: "40-73",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "100-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "214",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "38",
    name: "Sonic",
    groundCC: "-",
    shortHopCC: "45-69",
    clayCC: "",
    clayStanding: "69",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "31",
    airNWeakDown: "83",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Very High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "39",
    name: "King Dedede",
    groundCC: "-",
    shortHopCC: "37-85",
    clayCC: "",
    clayStanding: "85",
    ledgeSideTiltKO: "155",
    ledgeAirKO: "125",
    upSmashKO: "120",
    ledgeSideSmashKO: "90",
    upAirStrongKO: "125-150",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "100",
    sombrero: "165",
    airNDown: "38",
    airNWeakDown: "99",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "40.0",
    name: "Pikmin & Olimar (Red)",
    groundCC: "-",
    shortHopCC: "36-66",
    clayCC: "",
    clayStanding: "66",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "80",
    upThrowThunder: "196",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "○",
    upAirNeutralAir: ""
  },
  {
    id: "40.1",
    name: "Pikmin & Olimar (Yellow)",
    groundCC: "-",
    shortHopCC: "36-66",
    clayCC: "",
    clayStanding: "66",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "80",
    upThrowThunder: "196",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "○",
    upAirNeutralAir: ""
  },
  {
    id: "40.2",
    name: "Pikmin & Olimar (Blue)",
    groundCC: "-",
    shortHopCC: "36-66",
    clayCC: "",
    clayStanding: "66",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "80",
    upThrowThunder: "196",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "○",
    upAirNeutralAir: ""
  },
  {
    id: "40.3",
    name: "Pikmin & Olimar (White)",
    groundCC: "-",
    shortHopCC: "36-66",
    clayCC: "",
    clayStanding: "66",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "80",
    upThrowThunder: "196",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "○",
    upAirNeutralAir: ""
  },
  {
    id: "40.4",
    name: "Pikmin & Olimar (Purple)",
    groundCC: "-",
    shortHopCC: "36-66",
    clayCC: "",
    clayStanding: "66",
    ledgeSideTiltKO: "125",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-120",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "80",
    upThrowThunder: "196",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "○",
    upAirNeutralAir: ""
  },
  {
    id: "41.0",
    name: "Lucario (0%)",
    groundCC: "-",
    shortHopCC: "40-74",
    clayCC: "",
    clayStanding: "74",
    ledgeSideTiltKO: "175",
    ledgeAirKO: "145",
    upSmashKO: "135",
    ledgeSideSmashKO: "115",
    upAirStrongKO: "140-165",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "125",
    sombrero: "180",
    airNDown: "33",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "41.65",
    name: "Lucario (65%)",
    groundCC: "-",
    shortHopCC: "40-74",
    clayCC: "",
    clayStanding: "74",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "41.190",
    name: "Lucario (190%)",
    groundCC: "-",
    shortHopCC: "40-74",
    clayCC: "",
    clayStanding: "74",
    ledgeSideTiltKO: "105",
    ledgeAirKO: "75",
    upSmashKO: "65",
    ledgeSideSmashKO: "45",
    upAirStrongKO: "70-95",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "65",
    sombrero: "110",
    airNDown: "33",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "42",
    name: "R.O.B.",
    groundCC: "-",
    shortHopCC: "40-74",
    clayCC: "",
    clayStanding: "74",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "43",
    name: "Toon Link",
    groundCC: "-",
    shortHopCC: "40-70",
    clayCC: "",
    clayStanding: "70",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "95",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "80",
    sombrero: "140",
    airNDown: "31",
    airNWeakDown: "84",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "44",
    name: "Wolf",
    groundCC: "-",
    shortHopCC: "42-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "45",
    name: "Villager",
    groundCC: "-",
    shortHopCC: "38-69",
    clayCC: "",
    clayStanding: "69",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "31",
    airNWeakDown: "83",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "46",
    name: "Mega Man",
    groundCC: "-",
    shortHopCC: "40-73",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "47.0",
    name: "Wii Fit Trainer (Normal)",
    groundCC: "-",
    shortHopCC: "46-74",
    clayCC: "",
    clayStanding: "74",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "100",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "47.1",
    name: "Wii Fit Trainer (Deep Breathing)",
    groundCC: "-",
    shortHopCC: "42-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "100",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "48.0",
    name: "Rosalina & Luma (Rosalina)",
    groundCC: "-",
    shortHopCC: "37-68",
    clayCC: "",
    clayStanding: "68",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "90-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "81",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "48.1",
    name: "Rosalina & Luma (Luma)",
    groundCC: "-",
    shortHopCC: "37-68",
    clayCC: "",
    clayStanding: "68",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "90",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "90-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "81",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "49",
    name: "Little Mac",
    groundCC: "35-76",
    shortHopCC: "",
    clayCC: "",
    clayStanding: "76",
    ledgeSideTiltKO: "145",
    ledgeAirKO: "115",
    upSmashKO: "105",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "110-135",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "150",
    airNDown: "34",
    airNWeakDown: "90",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "50",
    name: "Greninja",
    groundCC: "-",
    shortHopCC: "40-69",
    clayCC: "",
    clayStanding: "69",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "31",
    airNWeakDown: "83",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "51",
    name: "Mii Brawler",
    groundCC: "-",
    shortHopCC: "40-72",
    clayCC: "",
    clayStanding: "72",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "52",
    name: "Mii Swordfighter",
    groundCC: "-",
    shortHopCC: "40-72",
    clayCC: "",
    clayStanding: "72",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "53",
    name: "Mii Gunner",
    groundCC: "-",
    shortHopCC: "40-72",
    clayCC: "",
    clayStanding: "72",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "54",
    name: "Palutena",
    groundCC: "-",
    shortHopCC: "39-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "55",
    name: "Pac-Man",
    groundCC: "-",
    shortHopCC: "40-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "56",
    name: "Robin",
    groundCC: "-",
    shortHopCC: "39-72",
    clayCC: "",
    clayStanding: "72",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "214",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "57.0",
    name: "Shulk (Normal)",
    groundCC: "-",
    shortHopCC: "41-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "57.1",
    name: "Shulk (Jump)",
    groundCC: "49-70",
    shortHopCC: "-",
    clayCC: "",
    clayStanding: "70",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-125",
    clayToSideSmash: "65-70",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "57.2",
    name: "Shulk (Speed)",
    groundCC: "-",
    shortHopCC: "43-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "57.3",
    name: "Shulk (Shield)",
    groundCC: "-",
    shortHopCC: "-",
    clayCC: "-",
    clayStanding: "-",
    ledgeSideTiltKO: "-",
    ledgeAirKO: "-",
    upSmashKO: "-",
    ledgeSideSmashKO: "-",
    upAirStrongKO: "-",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "-",
    sombrero: "-",
    airNDown: "105",
    airNWeakDown: "-",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "57.4",
    name: "Shulk (Buster)",
    groundCC: "-",
    shortHopCC: "41-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "90",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "88",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "57.5",
    name: "Shulk (Smash)",
    groundCC: "-",
    shortHopCC: "9-37",
    clayCC: "",
    clayStanding: "37",
    ledgeSideTiltKO: "100",
    ledgeAirKO: "80",
    upSmashKO: "70",
    ledgeSideSmashKO: "50",
    upAirStrongKO: "105-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "115",
    airNDown: "17",
    airNWeakDown: "59",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "58",
    name: "Bowser Jr.",
    groundCC: "-",
    shortHopCC: "40-73",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "59",
    name: "Duck Hunt",
    groundCC: "-",
    shortHopCC: "38-69",
    clayCC: "",
    clayStanding: "69",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "31",
    airNWeakDown: "83",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "60.0",
    name: "Ryu (Normal)",
    groundCC: "-",
    shortHopCC: "48-77",
    clayCC: "",
    clayStanding: "77",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "110",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "110-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "155",
    airNDown: "35",
    airNWeakDown: "91",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "60.1",
    name: "Ryu (Strong)",
    groundCC: "-",
    shortHopCC: "48-77",
    clayCC: "",
    clayStanding: "77",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "110",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "110-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "155",
    airNDown: "35",
    airNWeakDown: "91",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "60.2",
    name: "Ken (Normal)",
    groundCC: "-",
    shortHopCC: "48-77",
    clayCC: "",
    clayStanding: "77",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "110",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "110-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "155",
    airNDown: "35",
    airNWeakDown: "91",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "60.3",
    name: "Ken (Strong)",
    groundCC: "-",
    shortHopCC: "48-77",
    clayCC: "",
    clayStanding: "77",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "110",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "110-125",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "155",
    airNDown: "35",
    airNWeakDown: "91",
    upThrowThunder: "",
    downAirUpStrong: "○",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "61",
    name: "Cloud",
    groundCC: "-",
    shortHopCC: "41-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "89",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "62",
    name: "Corrin",
    groundCC: "-",
    shortHopCC: "40-73",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "63",
    name: "Bayonetta",
    groundCC: "-",
    shortHopCC: "38-69",
    clayCC: "",
    clayStanding: "69",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "31",
    airNWeakDown: "83",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "64",
    name: "Inkling",
    groundCC: "-",
    shortHopCC: "39-70",
    clayCC: "",
    clayStanding: "70",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "95",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "31",
    airNWeakDown: "84",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "65",
    name: "Ridley",
    groundCC: "-",
    shortHopCC: "41-80",
    clayCC: "",
    clayStanding: "80",
    ledgeSideTiltKO: "150",
    ledgeAirKO: "120",
    upSmashKO: "110",
    ledgeSideSmashKO: "85",
    upAirStrongKO: "115-140",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "155",
    airNDown: "36",
    airNWeakDown: "94",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "66",
    name: "Simon",
    groundCC: "-",
    shortHopCC: "41-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "89",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "66.1",
    name: "Richter",
    groundCC: "-",
    shortHopCC: "41-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "89",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "67",
    name: "King K. Rool",
    groundCC: "-",
    shortHopCC: "38-87",
    clayCC: "",
    clayStanding: "87",
    ledgeSideTiltKO: "155",
    ledgeAirKO: "125",
    upSmashKO: "120",
    ledgeSideSmashKO: "90",
    upAirStrongKO: "125-150",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "100",
    sombrero: "165",
    airNDown: "39",
    airNWeakDown: "101",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "68",
    name: "Isabelle",
    groundCC: "-",
    shortHopCC: "38-68",
    clayCC: "",
    clayStanding: "68",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "30",
    airNWeakDown: "82",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "69",
    name: "Incineroar",
    groundCC: "-",
    shortHopCC: "41-80",
    clayCC: "",
    clayStanding: "80",
    ledgeSideTiltKO: "150",
    ledgeAirKO: "120",
    upSmashKO: "110",
    ledgeSideSmashKO: "85",
    upAirStrongKO: "115-140",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "155",
    airNDown: "36",
    airNWeakDown: "94",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "70",
    name: "Piranha Plant",
    groundCC: "-",
    shortHopCC: "39-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "71.0",
    name: "Joker (Normal)",
    groundCC: "-",
    shortHopCC: "39-70",
    clayCC: "",
    clayStanding: "70",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "95",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "31",
    airNWeakDown: "84",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "71.1",
    name: "Joker (Arsene)",
    groundCC: "-",
    shortHopCC: "39-70",
    clayCC: "",
    clayStanding: "70",
    ledgeSideTiltKO: "115",
    ledgeAirKO: "85",
    upSmashKO: "75",
    ledgeSideSmashKO: "55",
    upAirStrongKO: "75-95",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "65",
    sombrero: "120",
    airNDown: "31",
    airNWeakDown: "84",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "72.0",
    name: "Hero (Normal)",
    groundCC: "-",
    shortHopCC: "40-73",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Medium",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "72.1",
    name: "Hero (Psych Up)",
    groundCC: "-",
    shortHopCC: "40-73",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "120",
    ledgeAirKO: "90",
    upSmashKO: "80",
    ledgeSideSmashKO: "60",
    upAirStrongKO: "85-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "75",
    sombrero: "125",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Medium",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "72.2",
    name: "Hero (Oomph)",
    groundCC: "-",
    shortHopCC: "40-73",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "120",
    ledgeAirKO: "90",
    upSmashKO: "80",
    ledgeSideSmashKO: "60",
    upAirStrongKO: "85-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "75",
    sombrero: "125",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Medium",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "72.3",
    name: "Hero (Acceleratle)",
    groundCC: "-",
    shortHopCC: "40-73",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "33",
    airNWeakDown: "87",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Medium",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "73",
    name: "Banjo & Kazooie",
    groundCC: "-",
    shortHopCC: "40-72",
    clayCC: "",
    clayStanding: "72",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "74",
    name: "Terry",
    groundCC: "-",
    shortHopCC: "42-76",
    clayCC: "",
    clayStanding: "76",
    ledgeSideTiltKO: "145",
    ledgeAirKO: "115",
    upSmashKO: "105",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "110-135",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "150",
    airNDown: "34",
    airNWeakDown: "90",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "75",
    name: "Byleth",
    groundCC: "-",
    shortHopCC: "41-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "89",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "76",
    name: "Min Min",
    groundCC: "-",
    shortHopCC: "39-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Normal",
    fastestLedgeStealInside: "○",
    slowestLedgeStealInside: "×",
    upAirNeutralAir: ""
  },
  {
    id: "76.1",
    name: "Sephiroth (Normal)",
    groundCC: "-",
    shortHopCC: "39-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Medium",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "76.2",
    name: "Sephiroth (One-Winged)",
    groundCC: "-",
    shortHopCC: "39-71",
    clayCC: "",
    clayStanding: "71",
    ledgeSideTiltKO: "115",
    ledgeAirKO: "85",
    upSmashKO: "80",
    ledgeSideSmashKO: "55",
    upAirStrongKO: "75-95",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "65",
    sombrero: "120",
    airNDown: "32",
    airNWeakDown: "85",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Medium",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "77.0",
    name: "Steve (Unequipped)",
    groundCC: "-",
    shortHopCC: "39-60",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "145",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "77.1",
    name: "Steve (Wood)",
    groundCC: "-",
    shortHopCC: "39-60",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "145",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "77.2",
    name: "Steve (Stone)",
    groundCC: "-",
    shortHopCC: "39-60",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "145",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "77.3",
    name: "Steve (Iron)",
    groundCC: "-",
    shortHopCC: "39-60",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "145",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "77.4",
    name: "Steve (Gold)",
    groundCC: "-",
    shortHopCC: "39-60",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "145",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "77.5",
    name: "Steve (Diamond)",
    groundCC: "-",
    shortHopCC: "39-60",
    clayCC: "",
    clayStanding: "73",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "100",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "70",
    sombrero: "145",
    airNDown: "32",
    airNWeakDown: "86",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "78",
    name: "Sephiroth",
    groundCC: "-",
    shortHopCC: "41-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "89",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "79",
    name: "Pyra",
    groundCC: "-",
    shortHopCC: "41-75",
    clayCC: "",
    clayStanding: "75",
    ledgeSideTiltKO: "140",
    ledgeAirKO: "110",
    upSmashKO: "100",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "105-130",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "145",
    airNDown: "34",
    airNWeakDown: "89",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "80",
    name: "Mythra",
    groundCC: "-",
    shortHopCC: "39-70",
    clayCC: "",
    clayStanding: "70",
    ledgeSideTiltKO: "135",
    ledgeAirKO: "105",
    upSmashKO: "95",
    ledgeSideSmashKO: "75",
    upAirStrongKO: "95-115",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "140",
    airNDown: "31",
    airNWeakDown: "84",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "81",
    name: "Kazuya",
    groundCC: "-",
    shortHopCC: "42-77",
    clayCC: "",
    clayStanding: "77",
    ledgeSideTiltKO: "145",
    ledgeAirKO: "115",
    upSmashKO: "105",
    ledgeSideSmashKO: "80",
    upAirStrongKO: "110-135",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "95",
    sombrero: "150",
    airNDown: "35",
    airNWeakDown: "91",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "Low",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  },
  {
    id: "82",
    name: "Sora",
    groundCC: "-",
    shortHopCC: "38-69",
    clayCC: "",
    clayStanding: "69",
    ledgeSideTiltKO: "130",
    ledgeAirKO: "100",
    upSmashKO: "95",
    ledgeSideSmashKO: "70",
    upAirStrongKO: "90-110",
    clayToSideSmash: "-",
    ccToSideSmash: "-",
    ledgesideAerialMeteor: "85",
    sombrero: "135",
    airNDown: "31",
    airNWeakDown: "83",
    upThrowThunder: "",
    downAirUpStrong: "×",
    ledgeSteal: "High",
    fastestLedgeStealInside: "",
    slowestLedgeStealInside: "",
    upAirNeutralAir: ""
  }];
